#!/bin/bash

# crontab:
# */1 * * * * ~/.bin/_plait-list-gc >> ~/log/_plait-list-gc.log 2>&1

player_state_file="/tmp/player-state"

is_apple_music_playing() {
    state=$(osascript -e 'tell application "Music" to player state as string' 2>/dev/null)
    if [[ "$state" == "playing" ]]; then
        return 0
    else
        return 1
    fi
}

if [ -f "$player_state_file" ]; then
    prev_state=$(cat "$player_state_file")
else
    prev_state="not_playing"
fi

if ! is_apple_music_playing; then
    if [ "$prev_state" = "not_playing" ]; then
        if [ "$(osascript -e 'tell application "Music" to delete (every playlist whose name is "_plait-list")')" == "Music" ]; then
            echo "_plait-list clobbered at $(date)"
        fi
    fi
    echo "not_playing" >"$player_state_file"
else
    echo "playing" >"$player_state_file"
fi
