#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
    echo 'script must be run by root' >&2
    exit 1
fi

if ! type bclm >//dev/null 2>&1; then
    echo 'bclm command not found, exiting' >&2
    exit 1
fi

has_battery() {
    pmset -g batt | grep -q 'InternalBattery'
}

is_not_plugged() {
    pmset -g batt | grep -q 'Battery Power'
}

is_plugged_and_not_charging() {
    pmset -g batt | grep -q 'AC Power' && pmset -g batt | grep -q 'charged'
}

is_plugged_and_charging() {
    pmset -g batt | grep -q 'AC Power' && pmset -g batt | grep -q 'charging'
}

get_bat_pct() {
    current_capacity=$(ioreg -l | grep -o '"CurrentCapacity" = [0-9]*' | awk '{print $3}')
    max_capacity=$(ioreg -l | grep -o '"MaxCapacity" = [0-9]*' | awk '{print $3}')
    percentage=$(echo "scale=2; ($current_capacity / $max_capacity) * 100" | bc)

    echo "$percentage"
}

if ! has_battery; then
    echo 'no battery found, exiting' >&2
    exit 1
fi

if is_not_plugged; then
    echo 'not plugged in, exiting' >&2
    exit 1
fi

current_bclm=$(bclm read)

if [ "$current_bclm" -eq 100 ] && batery_is_plugged_and_not_charging; then
    echo "bclm already set to 100 and battery not charging"
    exit 0
fi

default_bclm=81
bclm write 100
echo "bclm set to 100"

sleep 1
while is_plugged_and_charging; do
    echo "[charging] battery charged to $(get_bat_pct)%..."
    sleep 60
done

echo "[done] battery charged to $(get_bat_pct)%"
bclm write "$default_bclm"
echo "bclm reset to $default_bclm"
