#!/bin/bash

echo "Running 'dotfiles status'.."
source "$HOME/.config/shell/functions/dotfiles.sh" && dotfiles status
echo
echo "Running 'pass git status'.."
pass git status
echo
echo "Running 'git status' in ~/.config/nvim/.."
cd ~/.config/nvim && git status
echo
echo "Running 'git status' in ~/obsidian-vault/.."
cd ~/obsidian-vault/ && git status
echo
echo "Done."
