#!/bin/bash

. "$HOME/.bin/helpers/fancy-echo.sh"
. "$HOME/.config/shell/functions/dotfiles.sh"

blue_italic_echo "Running 'dotfiles status'..\n"
dotfiles status

blue_italic_echo "Running 'pass git status'..\n"
pass git status

blue_italic_echo "Running 'git status' in ~/.config/nvim..\n"
cd ~/.config/nvim && git status

blue_italic_echo "Running 'git status' in ${VAULT_PATH}.."
cd "$VAULT_PATH" && git status
