#!/bin/bash

this_computer=$(scutil --get ComputerName)

computers=("turnip" "sfizio" "cipolla")

for computer in "${computers[@]}"; do
    if [ "$this_computer" != "$computer" ]; then
        echo "🔄  running 'dot pull' on $computer.."
        ssh "$computer" 'zsh -i -c "dot pull"'
    fi
done
