#!/bin/bash

source "$HOME/.config/shell/env/colors.sh"
FORMAT="${ITALIC}${BLUE}%s${RESET}\n"

case "$(uname)" in
Darwin) this_computer=$(scutil --get ComputerName) ;;
Linux) this_computer=$(hostname) ;;
esac

timeout=30
computers=("turnip" "sfizio" "cipolla" "xicamatl")

for computer in "${computers[@]}"; do
    if [ "$this_computer" != "$computer" ]; then
        printf "$FORMAT" "Running 'dotfiles pull' on $computer.."
        ssh -o ConnectTimeout=${timeout} "$computer" "source ~/.config/shell/functions/dotfiles.sh && dotfiles pull"
    fi
done
