#!/bin/bash

duration="${1:-30}"

case "$(uname -s)" in
Linux*)
    /usr/bin/signal-desktop-beta --start-in-tray &
    sleep "$duration"
    pkill -f /usr/bin/signal-desktop-beta
    ;;
Darwin*)
    open -a "Signal" --args --start-in-tray &
    sleep "$duration"
    pkill -f "/Applications/Signal.app/Contents/MacOS/Signal"
    ;;
esac
