#!/usr/bin/env sh
# Append a UTF-8 NBSP to arguments or stdin

nbsp_bytes=$(printf '\302\240') # C2 A0

if [ "$#" -gt 0 ]; then
    printf '%s%s' "$*" "$nbsp_bytes"
else
    input=$(cat)
    # drop one trailing newline (common when piping from echo)
    input=${input%"\n"}
    printf '%s%s' "$input" "$nbsp_bytes"
fi
