#!/bin/bash

source "$HOME/.config/shell/env/colors.sh"
FORMAT="${ITALIC}${BLUE}%s${RESET}\n"

case "$(uname)" in
Darwin) this_computer=$(scutil --get ComputerName) ;;
Linux) this_computer=$(hostname) ;;
esac

timeout=17
computers=("turnip" "sfizio" "cipolla" "xicamatl")

for computer in "${computers[@]}"; do
    if [ "$this_computer" != "$computer" ]; then
        printf "$FORMAT" "Running 'git pull' in ~/.config/nvim on $computer.."
        ssh -o ConnectTimeout=${timeout} "$computer" "cd ~/.config/nvim; git pull"
    fi
done
