#!/bin/bash

wait_for() {
    func="$1"
    timeout_seconds=10
    elapsed_seconds=0
    while [ $elapsed_seconds -lt "$timeout_seconds" ]; do
        if "$func"; then
            return 0
        fi
        sleep 1
        elapsed_seconds=$((elapsed_seconds + 1))
    done
    return 1
}

is_vpn_connected() {
    mullvad status | grep "Connected" >/dev/null
}

tell() {
    local app_name="$1"
    local what="$2"

    if [ "$what" = "quit" ] && ! pgrep -x "$app_name" >/dev/null; then return 1; fi
    if [ "$what" = "activate" ] && pgrep -x "$app_name" >/dev/null; then return 1; fi

    echo "telling $app_name to $what.."
    osascript -e "tell application \"$app_name\" to $what" || return 1
    return 0
}

tell "Dropbox" "activate"

echo "starting full charge cycle.."
bclm-cc || exit 1

tell "Docker Desktop" "quit"
tell "Dropbox" "quit"

if ! is_vpn_connected; then
    # tell_app "Mullvad VPN" "activate"
    echo "telling mullvad to connect.."
    mullvad connect || exit 1
fi

if wait_for "is_vpn_connected"; then
    echo "vpn connected; undock!, undock!"
else
    echo "vpn failed to connect" >&2
    exit 1
fi
