#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo 'script must be run by root' >&2
    exit 1
fi

echo "starting full charge cycle.."
bclm-cc

echo "telling dropbox to quit.."
osascript -e 'tell application "Dropbox" to quit'

echo "undock!, undock!"
