#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo 'script must be run by root' >&2
    exit 1
fi

echo "starting full charge cycle.."
bclm-cc || exit 1

echo "telling dropbox to quit.."
osascript -e 'tell application "Dropbox" to quit'

echo "telling docker desktop to quit.."
osascript -e 'tell application "Docker Desktop" to quit'

echo "undock!, undock!"
