#!/bin/bash

source "$HOME/.config/shell/env/colors.sh"
FORMAT="${ITALIC}${BLUE}%s${RESET}\n"

printf "$FORMAT" "Running 'dotfiles pull'.."
source "$HOME/.config/shell/functions/dotfiles.sh" && dotfiles pull
echo
printf "$FORMAT" "Running 'pass git pull'.."
pass git pull
echo
printf "$FORMAT" "Running 'git pull' in ~/.config/nvim.."
cd ~/.config/nvim && git pull
echo
printf "$FORMAT" "Running 'git pull' in ${VAULT_PATH}.."
cd "$VAULT_PATH" && git pull
echo
printf "$FORMAT" "Running 'git pull' in ~/code/cv-joint.."
cd ~/code/cv-joint && git pull
