#!/bin/bash

. "$HOME/.bin/helpers/fancy-echo.sh"
. "$HOME/.config/shell/functions/dotfiles.sh"

blue_italic_echo "Running 'dotfiles pull'.."
dotfiles pull

blue_italic_echo "\nRunning 'pass git pull'.."
pass git pull

blue_italic_echo "\nRunning 'git pull' in ${NVIM_ROOT}.."
cd "$NVIM_ROOT" && git pull

blue_italic_echo "\nRunning 'git pull' in ${VAULT_ROOT}.."
cd "$VAULT_ROOT" && git pull

CV_JOINT_ROOT="$HOME/code/cv-joint/"
blue_italic_echo "\nRunning 'git pull' in $CV_JOINT_ROOT.."
cd "$CV_JOINT_ROOT" && git pull
