#!/bin/bash
set -eu

. "$HOME/.bin/helpers/fancy-echo.sh"
. "$HOME/.bin/helpers/parse-commit-message.sh"

commit_message="$(parse_message_arg "$@")"

blue_italic_echo "Syncing dotfiles.."
sync-dotfiles "$commit_message"

blue_italic_echo "\nSyncing pass.."
sync-pass

blue_italic_echo "\nSyncing nvim.."
sync-nvim "$commit_message"

blue_italic_echo "\nSyncing vault.."
sync-vault "$commit_message"
