#!/bin/sh
set -eu

GIT="git --git-dir=$VAULT_PATH/.git --work-tree=$VAULT_PATH"

. "$HOME/.bin/helpers/parse-commit-message.sh"
commit_message="$(parse_message_arg "$@")"

if [ -z "${commit_message:-}" ]; then
    hostname_value=$(hostname | sed 's/\.local$//')
    commit_message="$hostname_value vault sync"
fi

$GIT pull --no-edit

$GIT add -A

if ! $GIT diff --quiet || ! $GIT diff --cached --quiet; then
    $GIT commit -m "$commit_message"
fi

$GIT push
