#!/bin/bash
set -eu

. "$HOME/.bin/helpers/fancy-echo.sh"
. "$HOME/.bin/helpers/parse-commit-message.sh"

commit_message="$(parse_message_arg "$@")"

blue_italic_echo "Syncing dotfiles..\n"
sync-dotfiles "$commit_message"

blue_italic_echo "Syncing pass..\n"
sync-pass

blue_italic_echo "Syncing nvim..\n"
sync-nvim "$commit_message"

blue_italic_echo "Syncing vault.."
sync-vault "$commit_message"
