#!/bin/bash

. "$HOME/.bin/helpers/fancy-echo.sh"

blue_italic_echo "kiLliNg GPG agent.."
gpgconf --kill gpg-agent

blue_italic_echo "removing stale lock files.."
find ~/.gnupg -type f -name "*.lock" -delete

blue_italic_echo "restarting GPG agent.."
gpg-agent --daemon

blue_italic_echo "done."
